[package]
name = "iou_ownedparts"
version = "0.1.0"
authors = ["Jenna Magius <jenna@jenna.app>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iou = "0.3.3"
